Update SVN installation command to allow release info change
This solves the error:
Repository 'https://ppa.launchpadcontent.net/ondrej/php/ubuntu noble InRelease' changed its 'Label' value from '***** The main PPA for supported PHP versions with many PECL extensions *****' to 'PPA for PHP'

diff --git a/.github/workflows/phpunit.yml b/.github/workflows/phpunit.yml
--- a/.github/workflows/phpunit.yml
+++ b/.github/workflows/phpunit.yml
@@ -81,7 +81,7 @@ jobs:
         run: |
           if ! command -v svn &> /dev/null; then
             echo "Installing SVN..."
-            sudo apt-get update || { echo "Failed to update package lists"; exit 1; }
+            sudo apt-get update --allow-releaseinfo-change || { echo "Failed to update package lists"; exit 1; }
             sudo apt-get install -y subversion || { echo "Failed to install SVN"; exit 1; }
           else
             echo "SVN is already installed"
